### ISSUE TITLE
Some enums not generated for Java

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/generator#19]
## Summary

For the Java SDK, the generator fails to create the `com.algorand.algosdk.v2.client.model.Enums.Hashtype` class, but it still references from the `com.algorand.algosdk.v2.client.model.ProofResponse` class.

## Details

Using the following definitions:
* algod: https://github.com/algorand/go-algorand/blob/45f00972e7fa3d156c8773d75a17b0123c53c1b9/daemon/algod/api/algod.oas2.json
* indexer: https://github.com/algorand/indexer/blob/45c31dd95f7c98fb87b497b502b8e442170b8d79/api/indexer.oas2.json

**Comment by michaeldiamant** [comment]
I ran into the problem too without knowing about the issue's existence.  Here's what I understand bearing in mind that I've spent ~10min looking at generator source:

* _generator_ must generate all enums.  However, as of writing, it _only_ generates enums referenced by a _path_.
* Experimentation:
  * Here's a commit where I made `hashtype` an unreferenced _parameter_:   https://github.com/algorand/indexer/pull/1001/commits/94f520f5e57a4f89ae3387cf145edf1039692474.
  * The subsequent java-algorand-sdk code generation attempt _loses_ `hashtype` definition:  https://github.com/algorand/java-algorand-sdk/pull/320/commits/3b466a6de067c0e9de7645f4f5750aba91f2cc34#diff-ea9673314104617e2083d7f5dabb47d8853cae2d5cc41f75f64cefb5aa6014e2L55.
  * Once _generator_ handles unrefenced enums, then the code generation should _retain_ `hashtype`.

**Comment by FrankSzendzielarz** [comment]
Also misses Format enum which is implicitly defined as a referenced parameter. iirc there are one or two other enums in the ref'd parameters section. As an aside, there are a lot of referenced parameters defined in the spec, but not sure why. So the issue might be solvable by modifying the spec rather than the generator.

**Comment by Eric-Warehime** [comment]
Interesting, yeah. I think in terms of what is getting generated for the format options (at least for java), the queries are all just using "msgpack" and there is no configurable input where someone would supply an enum argument to get back json instead. 

I don't know whether or not it's the right decision to automatically generate things like this since they're not included in the model objects. Maybe this relates more to optimizing how our query code is being generated?

I think it would be better to have a separate issue for this if it's something that's a problem or can't be worked around if you're using templates instead of the Java generator which is not using the templates. 

Happy to look into this further and discuss solutions, but it seems separate to me so I'm going to close this one for now.

**Comment by FrankSzendzielarz** [comment]
Erm...actually yeah... Format is ignored but iirc you always get json back not msgpack right?

**Comment by FrankSzendzielarz** [comment]
Also the net sdks DO include enum referece vars as model objects because they are based on standard oas codegen. But not really important. I will leave them in as hardcoded utility classes until this codegen repo is brought up to scratch
